### ISSUE TITLE
Regional Director Section

### ISSUE THREAD

**Issue by pdx91** [pradyumna2905/Everwell-Website#14]
Change background color to white
Change text column widths to 1/3rd or similar

**Comment by chhaya456** [comment]
Hello,
I just made three following changes in Regional Director section:
1. changed background color to white
2.changed text column widths to 1/3rd
3. little slided up photo.

Please find attached screenshots of these changes.  Let me know  Is there anything missing? or Shall I go ahead and to make changes in original css file.

![regional director 1](https://cloud.githubusercontent.com/assets/14876912/10209137/5f6e6a28-678d-11e5-8c58-b366845febea.png)

![regional director 2](https://cloud.githubusercontent.com/assets/14876912/10209217/fc38fc38-678d-11e5-9670-32ff60625857.png)

Thank you,
Chhaya Parmar

**Comment by chhaya456** [comment]
Close #14
